### ISSUE TITLE
Specifying paths in Windows?

### ISSUE THREAD

**Issue by matyasselmeci** [opensciencegrid/stashcp#27]
How do you specify which path to copy from in Windows?  When I try

> stashcp.exe /chtc/PUBLIC/matyas/Python-3.6.2.tgz .

I get 

> unknown flag `chtc/PUBLIC/matyas/Python-3.6.2.tgz'

and when I try to use backslashes I just get a 403 forbidden error.

**Comment by djw8605** [comment]
Huh, good question.  In windows, arguments are usually specified with "/", right?  I haven't personally tested it.  Can you try quoting the path?

**Comment by matyasselmeci** [comment]
Yep, arguments are specified with "/" which is probably why it got confused. Quoting it didn't work (same error).

You could do some clever heuristic like treating it as a path if it's an invalid argument, or has more than one "/"; you could also turn "\" into "/" on Windows; you could change the argument prefix to "-" (SCP.EXE does that for example).

I just tried specifying the path as a URL, like

> stashcp.exe stash:///chtc/PUBLIC/matyas/Python-3.6.2.tgz .

which worked just fine.

**Comment by djw8605** [comment]
Interesting, so the protocol helps.

I use the package [go-flags](https://pkg.go.dev/github.com/jessevdk/go-flags) to help with option parsing, which has an option to turn of windows default option parsing and force posix style arguments, which may be best here.

**Comment by matyasselmeci** [comment]
Yeah I agree with that.  Windows seems to be moving away from `/`-based arguments as well -- PowerShell commands for example use `-`.

**Comment by matyasselmeci** [comment]
Fixed by #28 ; I tested it and it works. Thanks!
