### ISSUE TITLE
Specify valid caches from the namespaces.json

### ISSUE THREAD

**Issue by bbockelm** [opensciencegrid/stashcp#42]
Especially when it comes to authenticated caches, the permitted caches depends highly upon the namespaces in question -- a cache may serve LIGO and only LIGO.

The namespaces.json should accept a list of caches (including port numbers) that are acceptable for this part of the namespace.  The results from the GeoIP service should be filtered from this cache -- and we should only utilize the relevant port numbers.

**Comment by matyasselmeci** [comment]
@djw8605 is this done? I think this is in 6.8.1...

**Comment by djw8605** [comment]
Yeah, it's done.
